spring:  application:    name: STOCK-PRICE-API
      datasource:     username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    
  jpa:
    defer-datasource-initialization: true