INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES(111, 'SBI', 450.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES(112, 'HDFC', 550.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES(113, 'HCL', 650.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES(114, 'AXIS', 750.00);
